// Auto-generated by SvelteHybrid
// This API controller provides endpoints for dynamic page and component generation

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using System.Text;
using System.Text.Json;

namespace SvelteHybrid.Controllers;

/// <summary>
/// SvelteHybrid API for dynamic page/component generation (Development only)
/// </summary>
[ApiController]
[Route("api/sveltehybrid")]
public class SvelteHybridApiController : ControllerBase
{
    private readonly IWebHostEnvironment _env;

    public SvelteHybridApiController(IWebHostEnvironment env)
    {
        _env = env;
    }

    /// <summary>
    /// Generate a new reactive page
    /// </summary>
    [HttpPost("page")]
    public async Task<IActionResult> CreatePage([FromBody] CreatePageRequest request)
    {
        if (!_env.IsDevelopment())
            return Forbid("Only available in development mode");

        try
        {
            var viewPath = Path.Combine(_env.ContentRootPath, "Views", request.Controller ?? "Home");
            Directory.CreateDirectory(viewPath);

            var filePath = Path.Combine(viewPath, $"{request.Name}.cshtml");
            
            var content = GeneratePageContent(request);
            await System.IO.File.WriteAllTextAsync(filePath, content);

            return Ok(new { success = true, path = filePath, message = $"Page created: /Views/{request.Controller}/{request.Name}.cshtml" });
        }
        catch (Exception ex)
        {
            return BadRequest(new { success = false, error = ex.Message });
        }
    }

    /// <summary>
    /// Generate a new reactive component
    /// </summary>
    [HttpPost("component")]
    public async Task<IActionResult> CreateComponent([FromBody] CreateComponentRequest request)
    {
        if (!_env.IsDevelopment())
            return Forbid("Only available in development mode");

        try
        {
            var componentPath = Path.Combine(_env.ContentRootPath, "Views", "Shared", "Components", request.Name);
            Directory.CreateDirectory(componentPath);

            var filePath = Path.Combine(componentPath, "Default.cshtml");
            
            var content = GenerateComponentContent(request);
            await System.IO.File.WriteAllTextAsync(filePath, content);

            return Ok(new { success = true, path = filePath, message = $"Component created: {request.Name}" });
        }
        catch (Exception ex)
        {
            return BadRequest(new { success = false, error = ex.Message });
        }
    }

    /// <summary>
    /// List all reactive pages
    /// </summary>
    [HttpGet("pages")]
    public IActionResult ListPages()
    {
        var viewsPath = Path.Combine(_env.ContentRootPath, "Views");
        var pages = new List<object>();

        if (Directory.Exists(viewsPath))
        {
            foreach (var dir in Directory.GetDirectories(viewsPath))
            {
                var controller = Path.GetFileName(dir);
                foreach (var file in Directory.GetFiles(dir, "*.cshtml"))
                {
                    var content = System.IO.File.ReadAllText(file);
                    var isReactive = content.Contains("s-reactive");
                    
                    pages.Add(new
                    {
                        controller,
                        name = Path.GetFileNameWithoutExtension(file),
                        path = file,
                        isReactive,
                        url = $"/{controller}/{Path.GetFileNameWithoutExtension(file)}"
                    });
                }
            }
        }

        return Ok(pages);
    }

    /// <summary>
    /// Get SvelteHybrid status
    /// </summary>
    [HttpGet("status")]
    public IActionResult GetStatus()
    {
        return Ok(new
        {
            version = "3.0.0",
            environment = _env.EnvironmentName,
            isReady = true,
            features = new[]
            {
                "Reactive Components",
                "Two-way Binding",
                "Conditional Rendering",
                "Dynamic Lists",
                "Toast Notifications",
                "Modal Dialogs",
                "API Integration",
                "Form Handling"
            }
        });
    }

    private static string GeneratePageContent(CreatePageRequest request)
    {
        var sb = new StringBuilder();
        sb.AppendLine("@{");
        sb.AppendLine($"    ViewData[\"Title\"] = \"{request.Title ?? request.Name}\";");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"<h1>{request.Title ?? request.Name}</h1>");
        sb.AppendLine();
        sb.AppendLine("<div class=\"s-card\">");
        sb.AppendLine("    <div class=\"s-card-header\">{request.Title ?? request.Name}</div>");
        sb.AppendLine($"    <div class=\"s-card-body\" s-reactive s-data=\"{{ {request.InitialState ?? "count: 0"} }}\">");
        
        if (request.Components != null)
        {
            foreach (var comp in request.Components)
            {
                sb.AppendLine($"        <!-- {comp} -->");
            }
        }
        else
        {
            sb.AppendLine("        <p>Your reactive content here...</p>");
            sb.AppendLine("        <button class=\"s-btn s-btn-primary\" s-click=\"count++\">Count: {count}</button>");
        }
        
        sb.AppendLine("    </div>");
        sb.AppendLine("</div>");

        return sb.ToString();
    }

    private static string GenerateComponentContent(CreateComponentRequest request)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"@* {request.Name} Component - Auto-generated by SvelteHybrid *@");
        sb.AppendLine($"@model dynamic");
        sb.AppendLine();
        sb.AppendLine($"<div class=\"s-card\" s-reactive s-data=\"{{ {request.InitialState ?? ""} }}\">");
        sb.AppendLine($"    <div class=\"s-card-header\">{request.Name}</div>");
        sb.AppendLine($"    <div class=\"s-card-body\">");
        sb.AppendLine($"        @* Component content *@");
        sb.AppendLine($"    </div>");
        sb.AppendLine($"</div>");

        return sb.ToString();
    }
}

public class CreatePageRequest
{
    public string Name { get; set; } = "";
    public string? Title { get; set; }
    public string? Controller { get; set; }
    public string? InitialState { get; set; }
    public string[]? Components { get; set; }
}

public class CreateComponentRequest
{
    public string Name { get; set; } = "";
    public string? InitialState { get; set; }
    public string? Template { get; set; }
}
