// Auto-generated by SvelteHybrid
// This controller provides the demo page and component management

using Microsoft.AspNetCore.Mvc;

namespace SvelteHybrid.Controllers;

/// <summary>
/// SvelteHybrid demo and management controller
/// </summary>
public class SvelteHybridController : Controller
{
    /// <summary>
    /// Demo page showing all SvelteHybrid features
    /// </summary>
    public IActionResult Demo()
    {
        return View();
    }

    /// <summary>
    /// Documentation page
    /// </summary>
    public IActionResult Docs()
    {
        return View();
    }
}
